# Generated by Django 4.0.3 on 2022-03-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_junior_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
