# Generated by Django 4.0.3 on 2022-03-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_junior_jobs', '0002_alter_vacancy_published_at_alter_vacancy_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(),
        ),
    ]
