# Generated by Django 4.0.3 on 2022-03-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_junior_jobs', '0005_alter_vacancy_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary_max',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_min',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
